
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: jewelry_sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

  api:
    build: .
    container_name: jewelry_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal\SQLEXPRESS02;Database=CRM_Jewelry_workshop;Trusted_Connection=True;TrustServerCertificate=true;
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=JewelryCRM
      - Jwt__Audience=JewelryClient
    depends_on:
      - sqlserver
    restart: unless-stopped

volumes:
  sql_data: