services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jewelry_api_sqlite
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      # Подключение к SQLite (имя CRM_Jewelry_workshop)
      - ConnectionStrings__CRM_Jewelry_workshop=Data Source=/app/Data/SQLiteDatabase.db
      - Jwt__Key=${JWT_KEY:-supersecretkeywithatleast32characterslong!}
      - Jwt__Issuer=JewelryCRM
      - Jwt__Audience=JewelryClient
    volumes:
      # Том для хранения файла SQLite
      - sqlite_data:/app/Data
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local